version: '3'

services:
  condi:
    build:
      args:
        - APP_NAME=condi
      dockerfile: Dockerfile
    command: npm run start:dev:condi
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    volumes:
      - ./apps/condi:/app/apps/condi
      - ./libs/shared:/app/libs/shared
      - ./libs:/app/libs
      - ./.env.docker:/app/.env.docker
    depends_on:
      - users
      - rabbitmq

  users:
    build:
      args:
        - APP_NAME=users
      dockerfile: Dockerfile
    command: npm run start:dev:users
    env_file:
      - .env.docker
    volumes:
      - ./apps/users:/app/apps/users
      - ./libs/shared:/app/libs/shared
      - ./libs:/app/libs
      - ./.env.docker:/app/.env.docker
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"
      - "15672:15672"