version: '3'

services:
  condi:
    build:
      args:
        - APP_NAME=condi
      dockerfile: Dockerfile
    command: npm run start:dev:condi
    ports:
      - "4000:4000"
    env_file:
      - .env.docker
    volumes:
      - ./apps/condi:/app/apps/condi
      - ./libs:/app/libs
      - ./.env.docker:/app/.env.docker
    depends_on:
      - users
      - rabbitmq
      - condominiums

  users:
    build:
      args:
        - APP_NAME=users
      dockerfile: Dockerfile
    command: npm run start:dev:users
    env_file:
      - .env.docker
    volumes:
      - ./apps/users:/app/apps/users
      - ./libs:/app/libs
      - ./.env.docker:/app/.env.docker
    depends_on:
      - rabbitmq
  
  condominiums:
    build:
      args:
        - APP_NAME=condominiums
      dockerfile: Dockerfile
    command: npm run start:dev:condominiums
    env_file:
      - .env.docker
    volumes:
      - ./apps/condominiums:/app/apps/condominiums
      - ./libs:/app/libs
      - ./.env.docker:/app/.env.docker
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"